

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPV.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class SistemaPrestamosPVEntities : DbContext
{
    public SistemaPrestamosPVEntities()
        : base("name=SistemaPrestamosPVEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Deudores> Deudores { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Saldadore> Saldadores { get; set; }

    public virtual DbSet<BackUp> BackUps { get; set; }


    public virtual int backupdb()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("backupdb");
    }


    public virtual ObjectResult<Nullable<int>> spSumCuotasVencidas()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spSumCuotasVencidas");
    }

}

}

